id: P774F3755
initial_creation_type: input
source_metadata:
  title: 'BA: Proto-BA (Buddhanāmanirdeśa)'
  language: sa
  volumes:
    ea5edefd457a49c3831c35df6469ffc3:
      title: 'Chapter I: Nidāna'
      base_file: 'Chapter I: Nidāna.txt'
      work_id: WA1745BFA
    424530482f5c494fb1609059e1d5c588:
      title: 'Chapter II: Praṇidhānacaryā'
      base_file: 'Chapter II: Praṇidhānacaryā.txt'
      work_id: WBC0808BE
    c9cabc5c513a4aefa7a736f6e2eea632:
      title: Title
      base_file: Title.txt
      work_id: W132123D1
  chapter_to_tile: {}
created_at: '2022-03-01T21:20:26.678715'
last_modified_at: '2022-03-01T21:20:26.678720'
